# Header
menu:
  首页: /kana
  归档: /kana/archives
  关于: /kana/about
  分类: /kana/categories
  标签: /kana/tags
rss: /kana/atom.xml

# layout config
avatar: false
animation: false

# Content

description: I hate you.

