# Header
menu:
  首页: /kana
  归档: /kana/archives
  生活: /life
  分类: /kana/categories
  标签: /kana/tags
rss: /atom.xml

avatar: false

# Content
excerpt_link: Read More
description: I hate you.
animation: true
# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: