# Header
menu:
  首页: /kana
  归档: /kana/archives
  生活: /life
  分类: /kana/categories
  标签: /kana/tags
rss: /atom.xml

# layout config
avatar: false
animation: true
# Content
excerpt_link: Read More
description: I hate you.

# Miscellaneous

favicon: /favicon.png

