# Header
menu:
  首页: /
  归档: /archives
  生活: /life
rss: /atom.xml

# Content
excerpt_link: Read More
description: I hate you.

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id: